# file: roles/install-pgbouncer/tasks/configure.yml
---
- name: "Stage 2: stop pgbouncer service"
  service:
    name: pgbouncer
    state: stopped

- name: "Stage 2: create pgbouncer.ini"
  template:
    src: "{{ item }}.j2"
    dest: "{{ pgbouncer_conf }}/{{ item }}"
    owner: "{{ pgbouncer_admin_user }}"
    group: "{{ pgbouncer_admin_group }}"
    mode: 0600
  with_items:
    - pgbouncer.ini
    - userlist.txt

- name: "Stage 2: Enable and start pgbouncer"
  service:
    name: pgbouncer
    state: started
    enabled: yes
